analysis_name: 51NiTiSC_RAMS2TC_0Deg_1_9 # defaults to analysis

## working directory defaults to current working directory
## all relative paths specified herein are assumed to be in the working_dir
## any files not in working_dir should be specified with an absolute path
#working_dir: 

multiprocessing: -1 # "all", or "half", or -1 means all but one, defaults to -1

material:
  definitions: material_niti
  active: NiTi_cubic

image_series:
  file:
    stem: /media/DIFFRACTION/CHESS/2015/51NiTiSC_RAMS2TC_0Deg_1/9/ff/ff_%05d.ge2 # can include relative or absolute path
    ids: [1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105] # or can use globs: ["*2[4-9]"]
  images:
    start: 1
    stop: 3600
    step: 1
  omega:
    start: 0.0
    step: 0.1
    stop: 360.0
  dark: /media/DIFFRACTION/CHESS/2015/51NiTiSC_RAMS2TC_0Deg_1/10/ff/ff_01106.ge2
  flip: h # ~, v, h, hv, vh, cw, ccw

instrument:
  parameters: detector_55p6kev_chess_2015_dec.yml
  detector: # this section is only needed to convert old files to the new spec
    parameters_old: detector_61p332_CHESS_15_june_APS_cal_refined # the old detector spec, produced by the GUI
    pixels: # this section required to convert from old detector spec
      rows: 2048
      columns: 2048
      size: [0.200, 0.200] # [row height, col width] mm

pre_processing:
  ge_reader_threshold: 50  # Anything less than this will be set to zero on reading GE2 file
  min_blob_size: 10        # Blob containing less than these pixels will be discarded
  print_ge: false          # If true, GE2 files will be written to disk (pretty slow for now)
  radius_gray_dilation: 2  # When writing GE2 files, spot will be dilated by these pixels

find_orientations:
  orientation_maps:
    # A file name must be specified. If it doesn't exist, one will be created
    file: eta-omega.cpl

    threshold: 10
    bin_frames: 1 # defaults to 1

    ## "all", or a list of hkl orders used to find orientations
    ## defaults to all orders listed in the material definition
    active_hkls: all

  ## either search full quaternian grid, or seed search based on sparse
  ## orientation maps
  #use_quaternian_grid: some/file/name # defaults to seeded search
  seed_search: # this section is ignored if use_quaternian_grid is defined
    hkl_seeds: [0,1,2] # hkls ids to use, must be defined for seeded search
    fiber_step: 0.25 # degrees, defaults to ome tolerance

  threshold: 10 # defaults to 1

  omega:
    tolerance: 0.2 # in degrees, defaults to 2x ome step

  ## specify the branch cut, in degrees. The range must be 360 degrees.
  ## defaults to ["image_series:omega:start", "image_series:omega:start"+-360]
  ## depending on sign of "image_series:omega:step"
  period: [0.0, 360.0] # in degrees, defaults to full 360 starting at "ome start"

  eta:
    tolerance: 0.2 # in degrees, defaults to 2x ome step
    mask: 5 # degrees, mask angles close to ome rotation axis, defaults to 5

  clustering:
    radius: 0.25
    completeness: 0.6 # completeness threshold
    algorithm: fclusterdata # defaults to dbscan

  #extract_measured_g_vectors: true # defaults to false

fit_grains:
  do_fit: true # if false, extracts grains but doesn't fit. defaults to true

  #estimate: FePd_d_8/grains.out # defaults to None

  #npdiv: 1 # number of polar pixel grid subdivisions, defaults to 2

  panel_buffer: 10 # don't fit spots within this many pixels from edge

  threshold: 50

  tolerance:
    tth: [0.2, 0.2] # tolerance lists must be identical length
    eta: [1.0, 1.0]
    omega: [1.0, 1.0]

  tth_max: false # true, false, or a non-negative value, defaults to true

