#!/bin/bash

for dir in stack*/
do
    dir=${dir%*/}
    dir=${dir##*/}

    cd $dir
    montage -geometry 200x200 `ls -v layer_*_roi.png` montage_roi.png
    montage -geometry 200x200 `ls -v layer_*_watershed.png` montage_watershed.png
    cd ..
done
